before_script:
  - which sudo || (echo 'Acquire::http::Proxy "http://172.17.0.1:3128/";' >> /etc/apt/apt.conf && export HTTP_PROXY=172.17.0.1:3128 && apt-get update && apt-get -y install sudo)
  - sudo apt-get -y install git rsync curl wget debootstrap dh-make dpkg-dev
  - sudo apt-get -y install build-essential cmake pkg-config libboost-serialization-dev libboost-program-options-dev libboost-filesystem-dev libboost-graph-dev libopencv-dev qtbase5-dev qtbase5-dev-tools libglibmm-2.4-dev libcgal-dev geomview

stages:
  - build
  # TODO add tests
  #- test
  - deploy
  - package

# https://docs.gitlab.com/ee/ci/yaml/README.html#special-yaml-features
.job_template: &job_definition
  stage: build
  tags:
   - nodocker
  script:
    - if [ -d build/ ]; then rm -rf build/ ; fi
    - mkdir build/ && cd build/
    - cmake -DWITH_TESTS=OFF -DWITH_GUI=$WITH_GUI -DLIBUIPF_WITH_TESTS=OFF -DWITH_OPENCV=$WITH_OPENCV -DLIBUIPF_WITH_OPENCV=$WITH_OPENCV -DCMAKE_INSTALL_PREFIX=`pwd`/../prefix ../code
    - make -j 4
    - make install
  artifacts:
    expire_in: 1 week
    paths:
      - prefix/

build-uipf-with-cv:
  <<: *job_definition
  variables:
    WITH_OPENCV: 'ON'
    WITH_GUI: 'OFF'

build-uipf-without-cv:
  <<: *job_definition
  variables:
    WITH_OPENCV: 'OFF'
    WITH_GUI: 'OFF'

build-uipf-gui-with-cv:
  <<: *job_definition
  variables:
    WITH_OPENCV: 'ON'
    WITH_GUI: 'ON'

build-uipf-gui-without-cv:
  <<: *job_definition
  variables:
    WITH_OPENCV: 'OFF'
    WITH_GUI: 'ON'

deploy:
  stage: deploy
  tags:
   - nodocker
  script:
    # temporary solution for sharing uipf artifacts
    - rm -rf /tmp/uipf-prefix
    - rsync -a prefix/ /tmp/uipf-prefix
    - find /tmp/uipf-prefix |sort
  dependencies:
    - build-uipf-with-cv

artifact-packaging:
  stage: deploy
  tags:
   - nodocker
  script:
    - git clone git@gitlab.cebe.cc:master/packaging.git packaging
  artifacts:
    paths:
     - packaging/


variables:
  GIT_STRATEGY: clone

# build .deb packages
pkg_debian_jessie:
  image: debian:jessie
  tags:
   - docker
  stage: package
  dependencies:
   - artifact-packaging
  script:
#    - mkdir -p /tmp/${CI_BUILD_ID}-deb/src/uipf-2.0
#    - rsync -ar . /tmp/${CI_BUILD_ID}-deb/src/uipf-2.0
#    - mkdir ~/.ssh && ssh-keyscan -t rsa gitlab.cebe.cc >> ~/.ssh/known_hosts
#    - git clone git@gitlab.cebe.cc:master/packaging.git packaging
    - rsync -ar packaging/debian/ debian/
#    - cd /tmp/${CI_BUILD_ID}-deb/src/ && tar --exclude-vcs -czf uipf-2.0.tar.gz uipf-2.0
    - dpkg-buildpackage -us -uc -b
    - cp ../*.deb .
  environment:
    name: preview_packages
  when: manual
  only:
    - master
    - improved-data-model
    - packaging
  artifacts:
    paths:
     - '*.deb'
